name: resturant
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  digit_ui_components: ^0.0.2-dev.4
  digit_components: ^1.0.3
  auto_route: ^8.3.0
  flutter_bloc: ^8.1.5
  collection: ^1.18.0
  reactive_forms: ^17.0.0
  dart_mappable: ^4.2.2
  dio: ^5.4.3+1
  flutter_keyboard_visibility: ^5.4.1
  bloc_concurrency: ^0.2.5
  material_design_icons_flutter: ^7.0.7296
  sqflite: ^2.3.3

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  drift_dev: ^2.18.0
  auto_route_generator: ^8.0.0
  bloc_test: ^9.1.0
  dart_mappable_builder: ^4.2.2
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/Roboto/RobotoCondensed-Regular.ttf
  uses-material-design: true
