name: restaurant_app
description: A Flutter restaurant table booking and ordering app with offline SQLite storage.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Database
  sqflite: ^2.3.3+1
  path: ^1.9.0

  # Navigation
  auto_route: ^8.1.3

  # Local Storage
  shared_preferences: ^2.2.3

  # UI
  fluttertoast: ^8.2.6

  # Dependency Injection
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints & Code Generation
  flutter_lints: ^4.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.10

flutter:
  uses-material-design: true
